[tools]
node = "lts"
wrangler = "latest"

[env]
# in case of sharp/node-gpp error for wrangler in Mac
SHARP_IGNORE_GLOBAL_LIBVIPS = "1"

[tasks]
dev = "wrangler pages dev public --compatibility-date=2024-04-01"
"db:init" = "wrangler d1 execute relayx-db --local --file=schema.sql"
deploy = "wrangler pages deploy public"
"db:remote" = "wrangler d1 execute relayx-db --remote --file=schema.sql"
